name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: myapp
          POSTGRES_DB: myapp_test
          POSTGRES_PASSWORD: ""
        ports: ["5432:5432"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.0
        bundler-cache: true
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
          node-version: 15.x
    - name: Bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Setup test database
      env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: myapp
      run: bin/rails db:setup
    - name: Webpack compile:
      run: bundle exec rails webpacker:compile
    - name: Run tests
      env:
          RAILS_ENV: test
      run: bin/rails t
